image:
  file: Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
  - port: 4001
    onOpen: ignore
  - port: 4002
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
# Open up a terminal for each micro-service
# for each do and npm install in relevatn directory, note --prefix does the install in the directory specified
# then change to that directory
tasks:
  - name: client
    init: npm install --prefix blog/client
    command: cd blog/client
  - name: posts
    init: npm install --prefix blog/posts
    command: cd blog/posts
  - name: comments
    init: npm install --prefix blog/comments
    command: cd blog/comments
  
