image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
  - port: 4001
    onOpen: open-preview
  - port: 4002
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script' &&
             cd blog/client
  - command: cd blog/posts &&
             npm init -y &&
             npm install express cors axios nodeman
  - command: cd blog/comments && 
             npm init -y &&
             npm install express cors axios nodeman