image:
  file: Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000
    onOpen: open-preview
  - port: 4001
    onOpen: ignore
  - port: 4002
    onOpen: ignore

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: StartUp
    command: sudo chown -R $USER ~/.npm
    command: sudo chown -R $USER /usr/lib/node_modules
    command: sudo chown -R $USER /usr/local/lib/node_modules
    command: npm install && npm install -g cors && npm install -g axios && npm install -g nodemon
  - name: client
    command: cd blog/client
  - name: posts
    command: cd blog/posts 
  - name: comments
    command: cd blog/comments
  
