image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4000-4002
    onOpen: open-preview

# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - init: echo 'init script' # runs during prebuild
    command: echo 'start script' &&
             sudo npm init -y &&
             sudo npm install -g express cors axios nodemon &&
             cd blog/client 
  - command: cd blog/comments
  - command: cd blog/posts